### PR TITLE
Xmlformater test

### PR DESCRIPTION
**Pull request by peter279k**
# Change log

- add ```autoload-dev``` setting in ```composer.json```.
- remove the empty file in ```tests``` folder.
- add the ```ext-dom``` checking in ```composer.json```.
- add the XmlFormater tests (see [Travis CI build](https://travis-ci.org/peter279k/xml)).

### CODE REVIEW

**Comment by odan** [comment]
Hi @peter279k  :-)

Instead of reading/writing real files it would be nice to use a stream wrapper for a virtual file system like [mikey179/vfsStream](https://github.com/mikey179/vfsStream). What do you think?.

**Comment by peter279k** [comment]
Do you mean mock the saved formatted XML file in this [line](https://github.com/odan/xml/pull/1/files#diff-134c9ae4a9ab8a6779907d98aa57df8bR36)?

**Comment by odan** [comment]
Yes

**Comment by peter279k** [comment]
I use the ```vfsStream``` package to mock the file system when outputing the file.
And I also add the ```XmlValidator``` tests in this commit.

**Pull request merged**
